repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
- repo: https://github.com/deathbeds/prenotebook
  rev: 559648f4de3ce38741a7ffe34cce4f5b4d1c6a99
  hooks:
  - id: prenotebook
