repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
- repo: https://github.com/deathbeds/prenotebook
  rev: c72610c35d24965e0861981f4ca1925557356276
  hooks:
  - id: prenotebook
